baseurl = "/"
languageCode = "en-uk"
title = "Interactive figures - ORIGAMI 2018/19"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "A simple theme for Hugo"
  # "light" or "dark"
  defaultTheme = "dark"

[params.logo]
  logoText = "ORIGAMI 2018/19"
  # or
  #
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

[languages]
  [languages.en]
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"